spring:
  application:
    name: tachyon
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb:27017/${DATABASE}?authSource=${DATABASE}

springdoc:
  api-docs:
    path: /api-docs

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION_TIME}
